# SwiftLint Configuration for TCAKit

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - .git

# Rules to enable/disable
disabled_rules:
  - trailing_whitespace
  - todo

# Rules to enable
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 6

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - url
    - api

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60

# Custom rules for TCAKit
custom_rules:
  # Ensure public APIs have documentation
  public_api_documentation:
    name: "Public API Documentation"
    regex: '^public (class|struct|enum|protocol|func|var|let).*'
    message: "Public APIs should have documentation comments"
    severity: warning
    match_kinds:
      - comment
      - doccomment

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Reporter
reporter: "xcode"
