# SwiftLint Configuration for TCAKit

# Disable rules that don't apply well to our use case
disabled_rules:
  - empty_count  # We're comparing state.count (Int) to 0, not collection.count

# Configure rules
opt_in_rules:
  - redundant_discardable_let

# File patterns
included:
  - Sources
  - Tests

excluded:
  - .build
  - .git

# Line length
line_length:
  warning: 120
  error: 150

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 400
  error: 1000