name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add code samples to help explain your problem.
      placeholder: |
        ```swift
        import TCAKit
        
        // Your code here
        ```
      render: swift

  - type: dropdown
    id: swift-version
    attributes:
      label: Swift Version
      description: What version of Swift are you using?
      options:
        - Swift 5.9
        - Swift 5.10
        - Swift 5.11
        - Other
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) does this affect?
      options:
        - label: iOS
        - label: macOS
        - label: tvOS
        - label: watchOS
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - OS version
        - Xcode version (if applicable)
        - TCAKit version
      placeholder: |
        - macOS 14.0
        - Xcode 15.2
        - TCAKit 1.0.0

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
