name: Code Quality

on:
  push:
    branches: [ master, develop, B-002-store-core ]
  pull_request:
    branches: [ master, develop ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install SwiftLint
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      
    - name: Check Code Coverage
      run: |
        swift test --enable-code-coverage
        
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: .build/debug/codecov/default.profdata
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false


  dependency-check:
    name: Dependency Check
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Check for outdated dependencies
      run: |
        swift package show-dependencies --format json > dependencies.json
        echo "Dependencies checked successfully"
        
    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-report
        path: dependencies.json
