name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

env:
  XCODE_VERSION: '16.0'
  IOS_SIMULATOR: 'iPhone 16'
  IOS_VERSION: '18.6'
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

jobs:
  test:
    name: Test Release
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install SwiftLint
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      
    - name: Build Package
      run: swift build
      
    - name: Test Package
      run: swift test
      

  release:
    name: Create Release
    runs-on: macos-15
    needs: test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          Add TCAKit to your project using Swift Package Manager:
          
          ```swift
          dependencies: [
              .package(url: "https://github.com/ronstorm/tca-kit.git", from: "${{ github.ref_name }}")
          ]
          ```
          
          ## Documentation
          
          Documentation is available in the attached zip file.
        files: |
          .build/docs/*.zip
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-spm:
    name: Publish to Swift Package Index
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push' && !contains(github.ref_name, 'beta') && !contains(github.ref_name, 'alpha') && !contains(github.ref_name, 'rc')
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Notify Swift Package Index
      run: |
        curl -X POST "https://swiftpackageindex.com/api/packages" \
          -H "Content-Type: application/json" \
          -d '{"url": "https://github.com/ronstorm/tca-kit"}'
